services:
  container_jenkins-master:
    container_name: container_jenkins-master
    build: ./dockerfiles/jenkins/master
    image: image_jenkins-master:latest
    ports:
      - '9090:8080' # forwarding custom port host 9090 ke 8080 si containernya
      - '50000:50000' # dan ekspos 50000 utk para slavenya
    # volumes:
    #   - type: volume
    #     source: volume_jenkins_master
    #     target: /var/jenkins_home
    # networks:
    #   - network_jenkins
  # container_jenkins-agent:
  #   container_name: container_jenkins-agent
  #   build: ./dockerfiles/jenkins/agent
  #   image: image_jenkins-agent:latest
  #   ports:
  #     - '22:22' # buka port 22 utk koneksi ke master
  #   volumes:
  #     - type: volume
  #       source: volume_jenkins_agent
  #       target: /home/jenkins
  #   environment:
  #     - JENKINS_URL=http://container_jenkins-master:8080
  #     - JENKINS_AGENT_SSH_PUBKEY=your_ssh_pubkey
  #     - JENKINS_SECRET=your_secret
  #     - JENKINS_AGENT_NAME=node-slave
  #   networks:
  #     - network_jenkins

# volumes:
#   volume_jenkins_master:
#     driver: local
#   volume_jenkins_agent:
#     driver: local

# networks:
#   network_jenkins:
#     driver: bridge